In [1]:
25+6

31

In [2]:
#[],(),{} Containertypes 

In [3]:
a = [1,2,5,6,3,1,2]
b = {1:1,2:1,'name':'Leader'}
print(type(a))
print(len(a))

<class 'list'>
7


In [4]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [5]:
import math
math.sqrt(2)

1.4142135623730951

In [6]:
2**0.5

1.4142135623730951

In [7]:
import array as ar
a = ar.array('i',(1,2,3))
a

array('i', [1, 2, 3])

In [8]:
pip install numpy

In [9]:
import numpy as np
a = np.array(['1',2.5,3])
print(a)

['1' '2.5' '3']


In [10]:
a = np.array([[1.,2,3],(4,5,6)])
print(a)
print(a.size)
print(a.shape)
print(a.itemsize)

[[1. 2. 3.]
 [4. 5. 6.]]
6
(2, 3)
8


In [11]:
#For memory comparision
import sys #system specific parameters
print(sys.version)
S = range(1000)
print(type(S))
print(sys.getsizeof(125)*len(S))

3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
<class 'range'>
28000


In [12]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [13]:
import numpy as np
a=np.arange(25)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [15]:
D = np.arange(1000)
#print(D)
print(D.itemsize*D.size)

8000


In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [17]:
a = np.array([[1,2,3],[4,5,6]])
#print(a)
b = np.array([[4,5,6],[7,8,9]])
print(a+b)

[[ 5  7  9]
 [11 13 15]]


In [19]:
import random
for i in range(10):
  print(random.randint(999,9999))

3788
5124
9425
8297
4878
9567
5692
6599
2804
6722


In [20]:
data = np.random.rand(2,2) #range between 0 -1 
data

array([[0.62486011, 0.48158461],
       [0.4342881 , 0.51046202]])

In [21]:
data = np.random.randn(3,2)
data

array([[ 0.45757671,  0.91040379],
       [-0.88167509, -0.38161399],
       [ 0.3648434 ,  0.07260354]])

In [22]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
#print(a[:])
#print(a[0])
#print(a[1])
print(a[0,1:4])
print(a[0,1:])

[[1 2 3]
 [4 5 6]]
[2 3]
[2 3]


In [23]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a[0] #axis 0
a[1]

array([4, 5, 6])

In [25]:
#comprehension
a = {x:x for x in range(10)}
print(a)

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9}


In [26]:
data = {x:np.random.rand() for x in range(10)}
print(data)
data[5]

{0: 0.3211372105087533, 1: 0.23890132730210878, 2: 0.12639135881349972, 3: 0.20258137917344154, 4: 0.683769180701805, 5: 0.42761043244709185, 6: 0.10993300249909832, 7: 0.8281234778956309, 8: 0.08076637842527279, 9: 0.034976400690770015}


0.42761043244709185

In [27]:
a = np.array([[1,2,3],[4,5,6]])
print(np.mean(a))

3.5


In [28]:
np.var(a) #var = summation of (x - x(mean)square) / n - 1

2.9166666666666665

In [29]:
np.std(a)  #std is square root of variance

1.707825127659933