In [ ]:
import numpy as np
a=np.linspace(2,10,2)
a

array([ 2., 10.])

In [ ]:
a=np.arange(1.2,5.2)
a

array([1.2, 2.2, 3.2, 4.2])

In [ ]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
c = ([1,2,3],45,26)
print(len(c))
print(c)
b = np.asarray(c)
print(b)

3
([1, 2, 3], 45, 26)
[list([1, 2, 3]) 45 26]


# empty_like : Return an empty array with shape and type of input.
**ones_like**: Return an array of ones with shape and type of input.

 zeros_like: Return an array of zeros with shape and type of input.

 full_like : Return a new array with shape of input filled with value.

 empty : Return a new uninitialized array.
 ones : Return a new array setting values to one.
 zeros : Return a new array setting values to zero.
 full : Return a new array of given shape filled with value

In [ ]:
np.empty([1,2])

array([[ 2., 10.]])

In [ ]:
#empty creates an array whose initial content is random and 
#depends on the state of the memory
np.empty([3, 3])

array([[3.25837084e-316, 2.14321575e-312, 2.37663529e-312],
       [2.56761491e-312, 1.93101617e-312, 9.33678148e-313],
       [1.97345609e-312, 3.71326559e+161, 2.59452331e+161]])

In [ ]:
#Return a new array with the same shape and type as a given array.
a = np.array([[1,2,3],[4,5,6]])
print(a)
c = np.empty_like(a)
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.array([1,2,3])
a = np.ones_like(b)
print(a)

[1 1 1]


In [ ]:
a = np.ones_like((3,3))
a

array([1, 1])

In [ ]:
x = np.arange(6)
d = x.reshape(3,2)
e = np.ones_like(d)
print(d)
print(e)

[[0 1]
 [2 3]
 [4 5]]
[[1 1]
 [1 1]
 [1 1]]


In [ ]:
x = np.arange(6)
x = x.reshape((2, 3))
print(x)
print(np.ones_like(x))
#np.ones_like(x)

[[0 1 2]
 [3 4 5]]
[[1 1 1]
 [1 1 1]]


In [ ]:
print(np.zeros((3,2))) #2d array
print(np.zeros(10)) # 1d array

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(np.zeros_like((3,2)))

[0 0]


In [ ]:
a = np.array([1,2,3])
print(a)
b = np.full((1,3),26)
print(b)

[1 2 3]
[[26 26 26]]


In [ ]:
print(np.full((2,2),10))
print(np.full((3, 2), 5))

[[10 10]
 [10 10]]
[[5 5]
 [5 5]
 [5 5]]


In [ ]:
x = np.arange(6)
print(x)
np.full_like(x, 1)

[0 1 2 3 4 5]


array([1, 1, 1, 1, 1, 1])

In [ ]:
#Return a new array with the same shape and type as a given array.
print(np.eye(1,3))
print(np.identity(2))
#print(np.identity(5))

[[1. 0. 0.]]
[[1. 0.]
 [0. 1.]]


In [ ]:
#Extract a diagonal or construct a diagonal array.
x = np.arange(9).reshape((3,3))
print(x)
np.diag(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

In [ ]:
print(np.diag(x,k=1))

[1 5]


In [ ]:
#k>0 for diagonals above the main diagonal, 
#and k<0 for diagonals below the main diagonal.
print(np.diag(x, k=1))
print(np.diag(x,k=-1))

[1 5]
[3 7]


In [ ]:
#Permute the dimensions of an array.
arr = np.arange(16).reshape(4,4)
print(arr)
arr1 = np.arange(16).reshape((4, 2, 2))
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [ ]:
arr1

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [ ]:
arr1.transpose((2, 0, 1)) 
#number of sets,number of rows and number of columns

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15]]])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(np.sqrt(arr))
print(np.exp(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [ ]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([[1,2,3],[4,12,8]])
print(np.max(a))
print(np.min(a))

12
1


In [ ]:
#maximum 
np.max(arr)

9

In [ ]:
np.min(arr)

0

In [ ]:
x = np.random.rand(8).reshape(2,4)
print(x)
y = np.array([[1,2,3,5],[8,9,3,4]])
print(y)

[[0.30372878 0.27366314 0.0228258  0.47252377]
 [0.55186239 0.34338647 0.40214247 0.63555185]]
[[1 2 3 5]
 [8 9 3 4]]


In [ ]:
np.maximum(x,y)

array([[1., 2., 3., 5.],
       [8., 9., 3., 4.]])

In [ ]:
np.minimum(x,y)

array([[0.98113743, 0.14773883, 0.14319672, 0.21045177],
       [0.72014233, 0.4812493 , 0.74609754, 0.41346395]])

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7,8,9],[10,11,12]])
c = np.concatenate([arr1,arr2])
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([arr1,arr2],axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
a=1;b=a
b

1

In [ ]:
a=[1,2,3]
b =a
b[2] = 25
print(b)

[1, 2, 25]


In [ ]:
a

[1, 2, 25]

In [ ]:
a = [1,2,3]
b = a.copy()
print(b)

[1, 2, 3]


In [ ]:
b[1] = 25
b

[1, 25, 3]

In [ ]:
a

[1, 2, 3]

In [ ]:
a = np.array([(1,2,3,4),(3,1,4,2)]) 
print(a)

[[1 2 3 4]
 [3 1 4 2]]


In [ ]:
b = a.ravel() 
print(b)
b[0] = 25
print(b)
print(a)

[1 2 3 4 3 1 4 2]
[25  2  3  4  3  1  4  2]
[[25  2  3  4]
 [ 3  1  4  2]]


In [ ]:
#Ravel returns reference/view of original array 
#whereas flatten returns copy of original array.
#If you modify the array you would notice that the value of original array 
#also changes by using ravel.
import numpy as np 
# Create a numpy array 
a = np.array([(1,2,3,4),(3,1,4,2)]) 
# Let's print the array a 
print ("Original array:\n ")  
print(a) 
# To check the dimension of array (dimension =2) ( and type is numpy.ndarray ) 
print ("Dimension of array-> " , (a.ndim)) 
print("\nOutput for RAVEL \n")  
# Convert nd array to 1D array 
b = a.ravel() 
# Ravel only passes a view of original array to array 'b' 
print(b) 
b[0]=1000
print(b)

Original array:
 
[[1 2 3 4]
 [3 1 4 2]]
Dimension of array->  2

Output for RAVEL 

[1 2 3 4 3 1 4 2]
[1000    2    3    4    3    1    4    2]


In [ ]:
# Note here that value of original array 'a' at also a[0][0] becomes 1000 
print(a) 
print("\nOutput for FLATTEN \n")  
  
# Convert nd array to 1D array 
c = a.flatten() 
  
# Flatten passes copy of original array to 'c' 
print(c) 
c[0]=0
print(c) 
  
# Note that by changing value of c there is no affect on value of 
#original array 'a' 
print(a)

[[1000    2    3    4]
 [   3    1    4    2]]

Output for FLATTEN 

[1000    2    3    4    3    1    4    2]
[0 2 3 4 3 1 4 2]
[[1000    2    3    4]
 [   3    1    4    2]]


In [ ]:
'''
In 2008, developer Wes McKinney started developing pandas when in need of high
performance, flexible tool for analysis of data.

Pandas gives Python the ability to work with spreadsheet-like data for fast data 
loading,manipulating,aligning and merging -->Series and DataFrame 
DataFrame represents entire spreadsheet whereas Series is 
a single column of the 
DataFrame'''

In [ ]:
import pandas as pd
import numpy as np
a = np.array([1,2,3])
#pandas.Series(data,index,dtype,copy) -->index -->np.arange(n)
b = pd.Series(a)
print(b)
c = pd.Series(a,index=[4,5,6])
print(c)
e = {'name':'saketh','age':27}
#f = pd.Series(e,index=[1,2])
g =pd.Series(e)
print(f)
print(g)

0    1
1    2
2    3
dtype: int64
4    1
5    2
6    3
dtype: int64
1    NaN
2    NaN
dtype: object
name    saketh
age         27
dtype: object


In [ ]:
#Pandas --> Panel data
import pandas as pd
a = pd.Series([1,2,3],index=[4,5,6])
a

4    1
5    2
6    3
dtype: int64

In [ ]:
#Create a Series from a dict :
Data = {'a':0,'b':1,'c':2}
S = pd.Series(Data,index = ['b','c','d','a'])
print(S)

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64


In [ ]:
#pandas.DataFrame(data,index,columns,dtype,copy)

In [ ]:
#series of lists
data = [['Alex',10],['Bob',12],['Clarke',13]]
print(len(data))
df = pd.DataFrame(data)
df1 = pd.DataFrame(data,columns=['Name','Age'])
print(df)
print(df1)

3
        0   1
0    Alex  10
1     Bob  12
2  Clarke  13
     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [ ]:
data = {0:0,1:1,2:4,3:9}
df = pd.DataFrame(data,index=[1])
print(df)

   0  1  2  3
1  0  1  4  9


In [ ]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3',4])
#df = pd.DataFrame(data,index=range(4))
print(df)

        Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
4      Ricky   42


In [ ]:
#Creating a dataframe from a series
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

one  two
a    1    1
b    2    2
c    3    3
d    5    4

In [ ]:
a= pd.DataFrame({'name':'Saketh','place':'krmnr','age':26},index=[5])
a

name  place  age
5  Saketh  krmnr   26

In [ ]:
a = pd.DataFrame([1,4,5],columns=['k','s','r'])
a

ValueError: ignored

In [ ]:
a

name  place  age
5  Saketh  krmnr   26

In [ ]:
import pandas as pd
a= pd.DataFrame({'name':'Saketh','place':'krmnr','age':26},index=[5])
#a.index;
print(a.values)
print(a.dtypes)

[['Saketh' 'krmnr' 26]]
name     object
place    object
age       int64
dtype: object


In [ ]:
a.values

array([['Saketh', 'krmnr', 26]], dtype=object)

In [ ]:
a.columns

Index(['name', 'place', 'age'], dtype='object')

In [ ]:
a.dtypes

k    int64
s    int64
r    int64
dtype: object

In [ ]:
import pandas as pd
data = pd.DataFrame({'price':[95,25,85,41],
                     'ticker':['AXP','CSCO','DIS',None],
                     'company':['American Express','Cisco','Walt Disney',
                                'Microsoft']})
data

price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   None         Microsoft

In [ ]:
data['price']
#data[0]

0    95
1    25
2    85
3    41
Name: price, dtype: int64

In [ ]:
#Subsetting columns
data['price']

0    95
1    25
2    85
3    41
Name: price, dtype: int64

In [ ]:
data[['price','company']]

price           company
0     95  American Express
1     25             Cisco
2     85       Walt Disney
3     41         Microsoft

In [ ]:
data[['price','ticker']]

price ticker
0     95    AXP
1     25   CSCO
2     85    DIS
3     41   None

In [ ]:
data

price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   None         Microsoft

In [ ]:
#Subsetting rows 
#loc --> subset based on index label (row name)
#iloc -->subset based on row index (row number)
data.iloc[0]

price                    95
ticker                  AXP
company    American Express
Name: 0, dtype: object

In [ ]:
data.iloc[0]

price                    95
ticker                  AXP
company    American Express
Name: 0, dtype: object

In [ ]:
data

price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   None         Microsoft

In [ ]:
data.loc[1]['company']

'Cisco'

In [ ]:
data.loc[2]['price']

85

In [ ]:
data.iloc[2]['ticker']

'DIS'

In [ ]:
#Subsetting multiple rows
data.loc[2:]

price ticker      company
2     85    DIS  Walt Disney
3     41   None    Microsoft

In [ ]:
data.loc[[0,3,1]]

price ticker           company
0     95    AXP  American Express
3     41   None         Microsoft
1     25   CSCO             Cisco

In [ ]:
data.iloc[-1]

price             41
ticker          None
company    Microsoft
Name: 3, dtype: object

In [ ]:
data

price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   None         Microsoft

In [ ]:
data.iloc[-1]

price             41
ticker          None
company    Microsoft
Name: 3, dtype: object

In [ ]:
data

price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   None         Microsoft

In [ ]:
#Subsetting multiple rows and columns
data.iloc[[3,2],[2,1]] #2nd and 3 rd rows with 1st and 2nd columns

company ticker
3    Microsoft   None
2  Walt Disney    DIS

In [ ]:
data

price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   None         Microsoft

In [ ]:
data.count()

price      4
ticker     3
company    4
dtype: int64

In [ ]:
data.count(axis="columns")

0    3
1    3
2    3
3    2
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   price    4 non-null      int64 
 1   ticker   3 non-null      object
 2   company  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [ ]:
a= pd.DataFrame({'name':'Saketh','place':'krmnr','gender':'male'},index=[5])
a.describe()

name  place gender
count        1      1      1
unique       1      1      1
top     Saketh  krmnr   male
freq         1      1      1

In [ ]:
data.describe()

price
count   4.000000
mean   61.500000
std    33.798422
min    25.000000
25%    37.000000
50%    63.000000
75%    87.500000
max    95.000000

In [ ]:
#create a text file and check
a = pd.read_table("sample.txt")
#a = pd.read_table("sample.txt")
a

a b
0  0 1 
1   2 3
2   4 5

In [ ]:
a.values

array([['0 1 '],
       ['2 3'],
       ['4 5']], dtype=object)

In [ ]:
a = pd.read_table("ex1.csv")
a

a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [ ]:
a = pd.read_table("ex1.csv",sep=',')
a

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
a = pd.read_csv("ex1.csv")
a

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
a.columns

Index(['a', 'b', 'c', 'd', 'message'], dtype='object')

In [ ]:
a

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
a.head(1)

a  b  c  d message
0  1  2  3  4   hello

In [ ]:
a.tail(1)

a   b   c   d message
2  9  10  11  12     foo

In [ ]:
#To get only top two rows of the dataframe
a.head()

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
a.tail(1)

a   b   c   d message
2  9  10  11  12     foo

In [ ]:
a=pd.read_excel("ex1.xlsx")
a

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [ ]:
a["a"]

0    1
1    5
2    9
Name: a, dtype: int64

In [ ]:
tables = pd.read_html("/content/bank.html")
tables

[                             Bank Name  ...       Updated Date
 0                          Allied Bank  ...  November 17, 2016
 1         The Woodbury Banking Company  ...  November 17, 2016
 2               First CornerStone Bank  ...  September 6, 2016
 3                   Trust Company Bank  ...  September 6, 2016
 4           North Milwaukee State Bank  ...      June 16, 2016
 ..                                 ...  ...                ...
 542                 Superior Bank, FSB  ...    August 19, 2014
 543                Malta National Bank  ...  November 18, 2002
 544    First Alliance Bank & Trust Co.  ...  February 18, 2003
 545  National State Bank of Metropolis  ...     March 17, 2005
 546                   Bank of Honolulu  ...     March 17, 2005
 
 [547 rows x 7 columns]]

In [ ]:
len(tables)

1

In [ ]:
a = tables[0]
a.head()

Bank Name  ...       Updated Date
0                   Allied Bank  ...  November 17, 2016
1  The Woodbury Banking Company  ...  November 17, 2016
2        First CornerStone Bank  ...  September 6, 2016
3            Trust Company Bank  ...  September 6, 2016
4    North Milwaukee State Bank  ...      June 16, 2016

[5 rows x 7 columns]

In [ ]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 547 entries, 0 to 546
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   Bank Name              547 non-null    object
 1   City                   547 non-null    object
 2   ST                     547 non-null    object
 3   CERT                   547 non-null    int64 
 4   Acquiring Institution  547 non-null    object
 5   Closing Date           547 non-null    object
 6   Updated Date           547 non-null    object
dtypes: int64(1), object(6)
memory usage: 30.0+ KB


In [ ]:
#To check the count of missing values in a dataframe
a.isnull().sum()

Bank Name                0
City                     0
ST                       0
CERT                     0
Acquiring Institution    0
Closing Date             0
Updated Date             0
dtype: int64